config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'restaurants', to: 'restaurants#index', as: 'restaurants_index'
  post 'restaurants', to: 'restaurants#create'
  get 'search', to: 'restaurants#search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end

  def home
    @today = Date.today
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  RESTAURANTS = [
    { name: "Dishoom", address: "Shoreditch, London", category: "indian" },
    { name: "Sushi Samba", address: "City, London", category: "japanese" }
  ]
  def index
    @restaurants = RESTAURANTS
  end

  def search
    @category = params[:food_type]
    @restaurants = RESTAURANTS.select {|r| r[:category] == @category }
  end

  def create
     render plain: "Add to DB restaurant '#{params[:name]}' with address '#{params[:address]}' and category '#{params[:category]}'"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lacuillere</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About page</h1>
<p>New page</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<h1>Home page for la Cuillere</h1>
<h1>Today is <%= @today %></h1>


<form action="/restaurants" method="post">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <input type="text" name="name" placeholder="name of the restaurant">
  <input type="text" name="address" placeholder="address of the restaurant">
  <input type="text" name="category" placeholder="category of the restaurant">
  <input type="submit">
</form>

app/views/restaurants/index.html.erb
<h1>List of restaurants</h1>
<ul>
  <% @restaurants.each do |restaurant| %>
    <li>
      <h2><%= restaurant[:name] %></h2>
      <p>address: <%= restaurant[:address] %> category: <%= restaurant[:category] %></p>
    </li>
    <% end %>
</ul>

<form action="/search" method="get">
  <input type="text" name="food_type" placeholder="What kind of food?">
  <input type="submit">
</form>

app/views/restaurants/search.html.erb
<h1>Results for the research</h1>
<ul>
  <% @restaurants.each do |restaurant| %>
    <li>
      <h2><%= restaurant[:name] %></h2>
      <p>address: <%= restaurant[:address] %> category: <%= restaurant[:category] %></p>
    </li>
    <% end %>
</ul>

<%= link_to 'Go back', restaurants_index_path %>